import { useMemo, useState } from 'react';
import type { GraphProjection, Relationship } from '@vani/shared';

const colors:Record<string,string>={semantically_similar:'#8e6fdb',cites:'#6e8f87',cited_by:'#6e8f87',uses_as_baseline:'#e28c4b',compares_against:'#ce6d65',evaluates_on:'#d9aa3e',uses_method:'#4a83a8',extends:'#5f9364',contradicts:'#b44f5b'};

export function GraphCanvas({graph,selectedId,onSelect}:{graph:GraphProjection;selectedId?:string;onSelect:(id:string)=>void}){
  const [edge,setEdge]=useState<Relationship|null>(null);const [nodeHover,setNodeHover]=useState<GraphProjection['nodes'][number]|null>(null);const [listMode,setListMode]=useState(false);
  const layout=useMemo(()=>{const width=640,height=590,cx=width/2,cy=height/2;return new Map(graph.nodes.map((node,i)=>{const ring=i===0?0:1+Math.floor((i-1)/8);const index=i===0?0:(i-1)%8;const radius=ring*200;const angle=index/8*Math.PI*2+ring*.5;return [node.id,{...node,x:cx+Math.cos(angle)*radius,y:cy+Math.sin(angle)*radius}]}))},[graph.nodes]);
  if(listMode)return <div className="graph-list"><button className="button secondary" onClick={()=>setListMode(false)}>Show visual map</button><table><thead><tr><th>Source</th><th>Relationship</th><th>Target</th><th>Confidence</th></tr></thead><tbody>{graph.edges.map(e=><tr key={e.id}><td>{layout.get(e.sourceId)?.label}</td><td>{e.predicate.replaceAll('_',' ')}</td><td>{layout.get(e.targetId)?.label}</td><td>{Math.round(e.confidence*100)}%</td></tr>)}</tbody></table></div>;
  return <div className="graph-canvas"><button className="graph-access" onClick={()=>setListMode(true)}>Accessible table view</button><svg viewBox="0 0 640 590" role="img" aria-label={`Research map with ${graph.nodes.length} papers and ${graph.edges.length} relationships`}>
    <defs><filter id="shadow"><feDropShadow dx="0" dy="3" stdDeviation="5" floodOpacity=".16"/></filter></defs>
    {graph.edges.map(e=>{const a=layout.get(e.sourceId),b=layout.get(e.targetId);if(!a||!b)return null;return <g key={e.id} onMouseEnter={()=>setEdge(e)} onMouseLeave={()=>setEdge(null)}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={colors[e.predicate]??'#aaa'} strokeWidth={e.verificationStatus==='verified'?3:2} strokeDasharray={e.verificationStatus==='inferred'?'7 6':undefined}/><line className="edge-hit" x1={a.x} y1={a.y} x2={b.x} y2={b.y}/></g>})}
    {Array.from(layout.values()).map((node,i)=>{const selected=node.id===selectedId;const radius=selected?38:i===0?34:27;const year=node.year==null?'n.d.':String(node.year).slice(-2);const nodeCode=`${node.venue.toUpperCase()||'WORK'} · ${year}`;return <g className="graph-node" key={node.id} tabIndex={0} role="button" aria-label={`${node.label}, ${nodeCode}`} onMouseEnter={()=>{setNodeHover(node);setEdge(null)}} onMouseLeave={()=>setNodeHover(null)} onFocus={()=>setNodeHover(node)} onBlur={()=>setNodeHover(null)} onClick={()=>onSelect(node.id)} onKeyDown={e=>e.key==='Enter'&&onSelect(node.id)}><circle cx={node.x} cy={node.y} r={radius+5} fill="transparent"/><circle cx={node.x} cy={node.y} r={radius} fill={selected?'#24584e':i===0?'#3f766a':'#fffdf7'} stroke={selected?'#ffd36b':'#5f9a8c'} strokeWidth={selected?5:2} filter="url(#shadow)"/><text x={node.x} y={node.y+3} textAnchor="middle" className={selected||i===0?'node-invert':''}>{nodeCode}</text><foreignObject x={node.x-75} y={node.y+radius+8} width="150" height="52"><div className="node-label">{node.label}</div></foreignObject></g>})}
  </svg>{nodeHover&&<div className="node-tooltip"><div className="tooltip-kicker">{nodeHover.venue.toUpperCase()} · {nodeHover.year??'n.d.'}</div><strong>{nodeHover.label}</strong><p>{nodeHover.gist||'No contribution summary is stored yet.'}</p><span>Click to inspect complete publication details</span></div>}{edge&&<div className="edge-tooltip"><strong>{edge.predicate.replaceAll('_',' ')}</strong><span>{edge.verificationStatus} · {Math.round(edge.confidence*100)}% confidence</span><p>{edge.evidence?.[0]?.exactText||'Model-inferred from semantic similarity; no direct passage.'}</p></div>}</div>
}
