import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Download, FolderPlus, Inbox, LayoutList, MoreHorizontal, Network, Search } from 'lucide-react';
import { api } from '../api';
import { useWorkspace } from '../context';
import { EmptyState, ErrorNotice, Loading, Modal, PageHeader, VerificationBadge } from '../components/ui';

export function CollectionPage(){
  const queryClient=useQueryClient();const {collectionId,selected,toggle}=useWorkspace();const [search,setSearch]=useState('');const [showCreate,setShowCreate]=useState(false);const [view,setView]=useState<'table'|'cards'>('table');
  const collections=useQuery({queryKey:['collections'],queryFn:api.collections});
  const works=useQuery({queryKey:['works',collectionId],queryFn:()=>api.works(collectionId),enabled:Boolean(collectionId)});
  const active=collections.data?.items.find(c=>c.id===collectionId);const filtered=works.data?.items.filter(w=>w.title.toLowerCase().includes(search.toLowerCase())||w.authors.some(a=>a.family.toLowerCase().includes(search.toLowerCase())))??[];
  const create=useMutation({mutationFn:api.createCollection,onSuccess:()=>{queryClient.invalidateQueries({queryKey:['collections']});setShowCreate(false)}});
  const status=useMutation({mutationFn:({workId,value}:{workId:string;value:string})=>api.updateStatus(collectionId!,workId,value),onSuccess:()=>queryClient.invalidateQueries({queryKey:['works',collectionId]})});
  async function exportCollection(){if(!collectionId)return;const response=await api.exportBibtex(collectionId);if(!response.ok)return;const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${active?.name??'vani'}.bib`;link.click();URL.revokeObjectURL(url)}
  return <div className="page collection-page"><PageHeader eyebrow="Research workspace" title={active?.name??'Collections'} description={active?.description||'Organize papers into a durable, evidence-rich research workspace.'} actions={<><button className="button secondary" onClick={()=>setShowCreate(true)}><FolderPlus size={16}/>New collection</button><button className="button primary" disabled={!collectionId} onClick={exportCollection}><Download size={16}/>Export BibTeX</button></>}/>
    <div className="stats-row"><div><strong>{active?.memberCount??0}</strong><span>papers</span></div><div><strong>{filtered.filter(w=>w.verificationStatus.startsWith('verified')).length}</strong><span>verified</span></div><div><strong>0</strong><span>needs attention</span></div><div className="stat-accent"><strong>{selected.length}</strong><span>selected</span></div></div>
    <div className="toolbar"><label className="search-field"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter by title or author…"/></label><div className="segmented"><button className={view==='table'?'active':''} onClick={()=>setView('table')}><LayoutList size={15}/>List</button><button className={view==='cards'?'active':''} onClick={()=>setView('cards')}><Network size={15}/>Signals</button></div></div>
    {works.isLoading?<Loading/>:works.error?<ErrorNotice error={works.error}/>:!collectionId?<EmptyState icon={<Inbox/>} title="Create your first collection" body="Collections hold papers, annotations, questions, and discovery profiles together." action={<button className="button primary" onClick={()=>setShowCreate(true)}>Create collection</button>}/>:filtered.length===0?<EmptyState icon={<Inbox/>} title="This collection is ready for a seed" body="Add a paper, DOI, keyword, or idea from Discover."/>:
      <div className={`paper-table ${view}`} role="table" aria-label="Collection papers"><div className="paper-row paper-head" role="row"><span/><span>Paper</span><span>Year</span><span>Status</span><span>Verification</span><span>Key</span><span/></div>{filtered.map(work=><div className={`paper-row ${selected.some(w=>w.id===work.id)?'selected':''}`} role="row" key={work.id}><input aria-label={`Select ${work.title}`} type="checkbox" checked={selected.some(w=>w.id===work.id)} onChange={()=>toggle(work)}/><div><a href={`/read/${work.id}`} className="paper-title">{work.title}</a><small>{work.authors.map(a=>a.family).join(', ')||'Unknown author'} · {work.venue}</small></div><span>{work.year??'—'}</span><select aria-label="Reading status" defaultValue="inbox" onChange={e=>status.mutate({workId:work.id,value:e.target.value})}><option value="inbox">Inbox</option><option value="to_read">To read</option><option value="reading">Reading</option><option value="read">Read</option><option value="foundational">Foundational</option><option value="cited">Cited</option></select><VerificationBadge status={work.verificationStatus}/><code>{work.citationKey}</code><button className="icon-button" aria-label="More actions"><MoreHorizontal size={17}/></button></div>)}</div>}
    {showCreate&&<Modal title="New collection" onClose={()=>setShowCreate(false)}><form className="stack-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);create.mutate({name:String(data.get('name')),description:String(data.get('description'))})}}><label>Name<input required name="name" autoFocus placeholder="e.g. Terrain representations"/></label><label>Description<textarea name="description" rows={3} placeholder="What question does this collection support?"/></label><button className="button primary" disabled={create.isPending}>{create.isPending?'Creating…':'Create collection'}</button></form></Modal>}
  </div>
}
