import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Check, Compass, Lightbulb, LoaderCircle, Plus, SlidersHorizontal, Sparkles } from 'lucide-react';
import { api } from '../api';
import { useWorkspace } from '../context';
import { ErrorNotice, PageHeader } from '../components/ui';

export function DiscoverPage(){
  const [query,setQuery]=useState('semantic geometric terrain abstraction');const [sources,setSources]=useState(['openalex','crossref']);const [ran,setRan]=useState(false);const [added,setAdded]=useState<Set<string>>(new Set());const {collectionId}=useWorkspace();const client=useQueryClient();
  const discovery=useMutation({mutationFn:()=>api.discover(query,sources),onSuccess:()=>setRan(true)});
  const add=useMutation({mutationFn:async(candidate:any)=>{const work=await api.importCandidate(candidate);if(collectionId)await api.addMembers(collectionId,[work.id]);return {candidate,work}},onSuccess:({candidate})=>{setAdded(v=>new Set(v).add(candidate.externalId));client.invalidateQueries({queryKey:['works']});client.invalidateQueries({queryKey:['collections']})}});
  const toggleSource=(source:string)=>setSources(list=>list.includes(source)?list.filter(s=>s!==source):[...list,source]);
  return <div className="page discover-page"><PageHeader eyebrow="Continuous discovery" title="Follow an idea, not just a citation trail" description="Search multiple scholarly sources, then inspect why each work belongs near your research."/>
    <section className="seed-composer"><div className="seed-icon"><Lightbulb size={22}/></div><div className="seed-main"><label>Seed with an idea, keyword, title, or DOI</label><div className="seed-input"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&discovery.mutate()} placeholder="What should VANI explore?"/><button className="button primary" onClick={()=>discovery.mutate()} disabled={discovery.isPending||query.length<2}>{discovery.isPending?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>}Deep search</button></div><div className="source-toggles"><span>Sources</span>{['openalex','crossref'].map(source=><button key={source} className={sources.includes(source)?'checked':''} onClick={()=>toggleSource(source)}>{sources.includes(source)&&<Check size={11}/>} {source==='openalex'?'OpenAlex':'Crossref'}</button>)}<span className="coming">Semantic Scholar · DBLP · arXiv connectors next</span></div></div></section>
    <div className="discover-toolbar"><div><Compass size={17}/><strong>{discovery.data?.items.length??0} candidates</strong><span>Similarity-first · deduplicated</span></div><button className="button ghost"><SlidersHorizontal size={15}/>Ranking signals</button></div>
    {discovery.error&&<ErrorNotice error={discovery.error}/>} {!ran&&!discovery.isPending&&<div className="discovery-intro"><div className="orbit-art"><span/><span/><span/><i/></div><h2>Give VANI a direction</h2><p>It will search enabled sources and return a transparent, inspectable candidate set. Nothing enters your library until you choose it.</p></div>}
    <div className="candidate-list">{discovery.data?.items.map((item:any,index:number)=>{const key=item.externalId;const isAdded=added.has(key);return <article className="candidate" key={key}><div className="candidate-rank">{String(index+1).padStart(2,'0')}</div><div className="candidate-body"><div className="candidate-flags"><span>{item.year??'n.d.'}</span><span>{item.venue}</span><span className="source-label">{item.connector}</span></div><h3>{item.title}</h3><p className="authors">{item.authors?.map((a:any)=>`${a.given} ${a.family}`).join(', ')}</p><p className="abstract">{item.abstract||'No abstract returned by this source.'}</p><div className="why"><Sparkles size={14}/><div><strong>Why shown</strong><span>Strong keyword and concept overlap with “{query}”. Identifier and title duplicates were removed across sources.</span></div></div></div><aside><div className="match-ring" style={{'--score':`${Math.max(58,94-index*4)*3.6}deg`} as any}><strong>{Math.max(58,94-index*4)}</strong><small>match</small></div><button className={`button ${isAdded?'success':'secondary'}`} disabled={isAdded||add.isPending} onClick={()=>add.mutate(item)}>{isAdded?<Check size={15}/>:<Plus size={15}/>} {isAdded?'Added':'Add'}</button></aside></article>})}</div>
  </div>
}
