import { Link } from 'react-router-dom';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BookPlus, Search } from 'lucide-react';
import { api } from '../api';
import { WorkCard } from '../components/WorkCard';
import { ErrorNotice, Loading, Modal, PageHeader } from '../components/ui';
import { useWorkspace } from '../context';

export function LibraryPage(){const [q,setQ]=useState('');const[show,setShow]=useState(false);const client=useQueryClient();const workspace=useWorkspace();const works=useQuery({queryKey:['library',q],queryFn:()=>api.works(undefined,q)});const create=useMutation({mutationFn:api.addWork,onSuccess:()=>{client.invalidateQueries({queryKey:['library']});setShow(false)}});
return <div className="page"><PageHeader eyebrow="Canonical library" title="Every work, version, and source" description="The library keeps verified metadata and user corrections separate from source assertions." actions={<><Link className="button secondary" to="/imports">Import research</Link><button className="button primary" onClick={()=>setShow(true)}><BookPlus size={16}/>Add paper</button></>}/><div className="toolbar"><label className="search-field"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search titles, authors, abstracts, identifiers…"/></label></div>{works.isLoading?<Loading/>:works.error?<ErrorNotice error={works.error}/>:<div className="work-grid">{works.data?.items.map(work=><WorkCard key={work.id} work={work} selected={workspace.selected.some(w=>w.id===work.id)} onSelect={()=>workspace.toggle(work)}/>)}</div>}
{show&&<Modal title="Add a paper" onClose={()=>setShow(false)}><form className="stack-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);create.mutate({title:String(d.get('title')),year:Number(d.get('year'))||null,venue:String(d.get('venue')),doi:String(d.get('doi'))||null,authors:[{given:String(d.get('given')),family:String(d.get('family'))}]})}}><label>Title<input required name="title" autoFocus/></label><div className="form-row"><label>First author given name<input name="given"/></label><label>Family name<input required name="family"/></label></div><div className="form-row"><label>Year<input name="year" type="number"/></label><label>Venue<input name="venue"/></label></div><label>DOI<input name="doi" placeholder="10.…"/></label>{create.error&&<ErrorNotice error={create.error}/>}<button className="button primary" disabled={create.isPending}>{create.isPending?'Adding…':'Add to library'}</button></form></Modal>}</div>}
