import { useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import { BookOpen, FileUp, Highlighter, Link2, MessageCircle, Save, Search, StickyNote } from 'lucide-react';
import { api } from '../api';
import { useWorkspace } from '../context';
import { EmptyState, ErrorNotice, Loading, PageHeader, VerificationBadge } from '../components/ui';

export function ReaderPage(){const {workId}=useParams();const workspace=useWorkspace();const id=workId??workspace.selected[0]?.id;const [tab,setTab]=useState<'notes'|'citation'>('notes');const [note,setNote]=useState('');const fileRef=useRef<HTMLInputElement>(null);const client=useQueryClient();const work=useQuery({queryKey:['work',id],queryFn:()=>api.work(id!),enabled:Boolean(id)});const notes=useQuery({queryKey:['notes',id],queryFn:()=>api.notes(undefined,id),enabled:Boolean(id)});const attachments=useQuery({queryKey:['attachments',id],queryFn:async()=>{const r=await fetch(`/api/v1/works/${id}/attachments`);if(!r.ok)throw new Error('Could not load attachments');return r.json() as Promise<{items:any[]}>},enabled:Boolean(id)});
const upload=useMutation({mutationFn:(file:File)=>api.uploadPdf(id!,file),onSuccess:()=>client.invalidateQueries({queryKey:['attachments',id]})});const save=useMutation({mutationFn:()=>api.createNote({title:`Reading notes — ${work.data?.citationKey}`,markdown:note,noteType:'source',workId:id}),onSuccess:()=>{setNote('');client.invalidateQueries({queryKey:['notes',id]})}});const attachment=attachments.data?.items[0];
if(!id)return <div className="page"><PageHeader title="Read" description="A version-aware place to read, annotate, and connect evidence."/><EmptyState icon={<BookOpen/>} title="Choose a paper to begin" body="Select a paper in a collection or the library, then return here."/></div>;
if(work.isLoading)return <Loading/>;if(work.error)return <ErrorNotice error={work.error}/>;if(!work.data)return null;
return <div className="reader-page"><header className="reader-header"><div><div className="eyebrow">{work.data.manifestationType.replaceAll('_',' ')} · {work.data.year}</div><h1>{work.data.title}</h1><div className="reader-meta"><span>{work.data.authors.map(a=>a.family).join(', ')}</span><VerificationBadge status={work.data.verificationStatus}/><code>{work.data.citationKey}</code></div></div><div className="reader-tools"><button className="icon-button"><Search size={17}/></button><button className="icon-button"><Highlighter size={17}/></button><input ref={fileRef} hidden type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&upload.mutate(e.target.files[0])}/><button className="button secondary" onClick={()=>fileRef.current?.click()}><FileUp size={16}/>{attachment?'Replace PDF':'Attach PDF'}</button></div></header>
<div className="reader-layout"><aside className="outline"><div className="panel-title"><BookOpen size={15}/><strong>Paper outline</strong></div>{['Abstract','Introduction','Related work','Method','Experiments','Limitations','References'].map((section,i)=><button className={i===0?'active':''} key={section}><span>{String(i+1).padStart(2,'0')}</span>{section}</button>)}<div className="document-fingerprint"><span>Document identity</span><code>{attachment?.object_hash?.slice(0,16)??'No PDF hash'}…</code><small>{work.data.manifestationType}</small></div></aside>
<main className="document-view">{upload.isPending?<Loading label="Hashing and storing the original PDF…"/>:attachment?<iframe title={work.data.title} src={`/api/v1/attachments/${attachment.id}/content#view=FitH`}/>:<div className="reflow-paper"><div className="paper-sheet"><h2>{work.data.title}</h2><p className="byline">{work.data.authors.map(a=>`${a.given} ${a.family}`).join(', ')}</p><h3>Abstract</h3><p>{work.data.abstract||'No abstract is available. Attach the PDF to begin reading and annotating.'}</p><button className="upload-drop" onClick={()=>fileRef.current?.click()}><FileUp/><strong>Attach the paper PDF</strong><span>The immutable original is stored by SHA-256.</span></button></div></div>}</main>
<aside className="evidence-pane"><div className="tab-row"><button className={tab==='notes'?'active':''} onClick={()=>setTab('notes')}><StickyNote size={14}/>Notes</button><button className={tab==='citation'?'active':''} onClick={()=>setTab('citation')}><Link2 size={14}/>Citation</button></div>{tab==='notes'?<><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Capture a claim, question, limitation, or connection…" rows={6}/><button className="button primary full" onClick={()=>save.mutate()} disabled={!note.trim()||save.isPending}><Save size={14}/>Save note</button><div className="saved-notes">{notes.data?.items.map(item=><article key={item.id}><strong>{item.title}</strong><p>{item.markdown}</p></article>)}</div></>:<div className="citation-card"><VerificationBadge status={work.data.verificationStatus}/><code>{work.data.citationKey}</code><dl><dt>Title</dt><dd>{work.data.title}</dd><dt>Venue</dt><dd>{work.data.venue}</dd><dt>DOI</dt><dd>{work.data.doi??'Not verified'}</dd></dl></div>}<a className="ask-link" href={`/ask?work=${id}`}><MessageCircle size={16}/><span><strong>Ask about this paper</strong><small>Use its evidence in context</small></span></a></aside></div></div>}
