import { useQuery } from '@tanstack/react-query';
import { Check, Cloud, Database, HardDrive, KeyRound, Lock, RefreshCw, Server, ShieldCheck } from 'lucide-react';
import { api } from '../api';
import { ErrorNotice, Loading, PageHeader } from '../components/ui';

export function SettingsPage(){const health=useQuery({queryKey:['health'],queryFn:api.health});const caps=useQuery({queryKey:['capabilities'],queryFn:api.capabilities});return <div className="page settings-page"><PageHeader eyebrow="Local-first control" title="Settings" description="VANI keeps research data on this machine and makes every external boundary explicit."/>{health.isLoading?<Loading/>:health.error?<ErrorNotice error={health.error}/>:<div className="settings-grid"><section className="settings-card"><header><div className="setting-icon green"><Server/></div><div><h2>VANI service</h2><p>Application and database status</p></div><span className="status-online"><i/>Online</span></header><dl><dt>Version</dt><dd>{health.data?.version}</dd><dt>API</dt><dd>127.0.0.1:8080</dd><dt>Storage</dt><dd>PostgreSQL + content-addressed files</dd></dl></section>
<section className="settings-card"><header><div className="setting-icon amber"><Cloud/></div><div><h2>Scholarly sources</h2><p>Metadata and discovery connectors</p></div></header><div className="connector-list">{['OpenAlex','Crossref'].map(name=><div key={name}><span><i className="connector-logo">{name[0]}</i><strong>{name}</strong></span><b><Check size={13}/>Enabled</b></div>)}{['Semantic Scholar','DBLP','arXiv','OpenReview'].map(name=><div className="muted" key={name}><span><i className="connector-logo">{name[0]}</i><strong>{name}</strong></span><button>Configure</button></div>)}</div></section>
<section className="settings-card"><header><div className="setting-icon blue"><ShieldCheck/></div><div><h2>Privacy routing</h2><p>What can leave this machine</p></div></header><label className="switch-row"><span><strong>Remote model for open-access text</strong><small>Only bounded evidence excerpts</small></span><input type="checkbox" defaultChecked={Boolean(caps.data?.remoteAsk)}/></label><label className="switch-row"><span><strong>Remote model for private notes</strong><small>Off by default</small></span><input type="checkbox"/></label><label className="switch-row"><span><strong>External search in Ask VANI</strong><small>Requires explicit per-question scope</small></span><input type="checkbox"/></label></section>
<section className="settings-card"><header><div className="setting-icon violet"><Database/></div><div><h2>Data stewardship</h2><p>Backups, integrity, and portability</p></div></header><button className="setting-action"><HardDrive size={17}/><span><strong>Create verified backup</strong><small>Database, objects, and hash manifest</small></span><RefreshCw size={15}/></button><button className="setting-action"><KeyRound size={17}/><span><strong>Connector credentials</strong><small>Secrets never appear in API responses</small></span><Lock size={15}/></button></section></div>}<footer className="settings-foot">VANI 0.1 · Local workspace · <a href="https://github.com" target="_blank">Documentation</a></footer></div>}
